name: shoppingcart_CICD

on:
  workflow_dispatch:
  push:
    paths:
     - 'shopping-cart/**'

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build War File
        run: cd ./shopping-cart && mvn package && cd ..
      -
        name: Build and Push WebApi
        uses: docker/build-push-action@v2
        with:
          context: ./shopping-cart
          file: shopping-cart/Dockerfile
          push: true
          tags: cloudcompdocker/shoppingcart-webapi:latest
      -
        name: Build and Push Database
        uses: docker/build-push-action@v2
        with:
          context: ./shopping-cart/db
          file: shopping-cart/db/Dockerfile
          push: true
          tags: cloudcompdocker/shoppingcart-database:latest
      - 
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GK_KEY }}
          project_id: ${{ secrets.GK_PROJECT_ID }}
      - 
        run: |-
          gcloud container clusters get-credentials "cluster-1" --zone "us-central1-c"
      - 
        name: Update Deployment and Services
        run: |-
          kubectl apply -f ./shopping-cart/namespace.yaml
          kubectl apply -f ./shopping-cart/service.yaml
          kubectl apply -f ./shopping-cart/deployment.yaml
      - 
        name: Deploy
        run: |-
          kubectl rollout restart -f ./shopping-cart/deployment.yaml --namespace shoppingcart-environment
